// Generated by bin/vendor-lily.mjs. Do not edit.
// The themes vendored into static/assets/themes/, offered by the theme picker.
export const themes = [
	"light",
	"dark",
	"dim",
	"night",
	"winter",
	"nord",
	"silk",
	"corporate",
	"business",
	"lofi",
	"retro",
	"sunset",
	"united-kingdom-government-digital-service",
	"united-kingdom-national-health-service-england-for-patients",
	"united-kingdom-national-health-service-england-for-practitioners",
	"united-kingdom-national-health-service-scotland-for-patients",
	"united-kingdom-national-health-service-scotland-for-practitioners",
	"united-kingdom-national-health-service-wales-for-patients",
	"united-kingdom-national-health-service-wales-for-practitioners",
	"united-states-web-design-system"
];
